version: "3.8"

services:
  scripted-echoes:
    container_name: scripted-echoes-dev
    image: scripted-echoes-dev
    build:
      context: ..
      target: development
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
