version: "3.8"

services:
  app:
    container_name: scripted-echoes-dev
    image: scripted-echoes-dev
    build:
      context: ..
      target: development
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
